FROM debian:sid-slim

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends imagemagick && apt-get -y autoremove --purge && apt-get clean

RUN adduser cnf && \
    gpasswd -a cnf sudo && \
    echo 'Defaults visiblepw'             >> /etc/sudoers && \
    echo 'cnf ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    echo 'Set disable_coredump false' > /etc/sudo.conf

WORKDIR /work

USER cnf
